# https://taskfile.dev

version: '3'

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

tasks:
  build:
    cmds:
      - mvnw clean compile

  run:
    cmds:
      - mvnw clean spring-boot:run -Dspring-boot.run.jvmArguments="-Denv=dev -Dapollo.configService=http://localhost:8080"


  
