app:
  id: "SampleApp"

apollo:
  bootstrap:
    enabled: false
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application,bifrost.yml
  configService: http://localhost:8080

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/starter_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port : 10080


logging:
  level:
    com:
      spring:
        ibatis:
          UserMapper: debug


management:
  endpoint:
    health:
      show-details: always