app:
  id: "SampleApp"

apollo:
  bootstrap:
    enabled: true
    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
    namespaces: application
  configService: http://localhost:8080

spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/starter_db
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port : 10080
